= Neo4j Graph Algorithms Jupyter Notebooks

This repository contains Jupyter Notebooks for each of the https://neo4j-contrib.github.io/neo4j-graph-algorithms/[Neo4j graph algorithms^].


== Path finding

* link:notebooks/AllPairsShortestPath.ipynb[All Pairs Shortest Path^]
* link:notebooks/SingleSourceShortestPath.ipynb[Single Source Shortest Path^]

== Centrality

* link:notebooks/DegreeCentrality.ipynb[Degree Centrality^]
* link:notebooks/ClosenessCentrality.ipynb[Closeness Centrality^]
* link:notebooks/BetweennessCentrality.ipynb[Betweenness Centrality^]

== Community Detection

* link:notebooks/StronglyConnectedComponents.ipynb[Strongly Connected Components^]
* link:notebooks/WeightedConnectedComponents.ipynb[Weighted Union Find^]
* link:notebooks/UnweightedConnectedComponents.ipynb[Unweighted Union Find^]
* link:notebooks/LabelPropagation.ipynb[Label Propagation^]
* link:notebooks/Louvain.ipynb[Louvain^]
* link:notebooks/TriangleCounting.ipynb[Triangle Counting^]

== Run the notebooks locally

If we want to run the notebooks locally you'll need to first install some required libraries.

I use https://virtualenv.pypa.io/en/stable/[virtualenv^] but that's just one option.
We can run the following set of commands to create a Python environment with the libraries installed:

```
virtualenv a
. a/bin/activate
pip install -r requirements.txt
```

We're now ready to launch the Jupyter server.

The notebooks assume that there's a Neo4j server running at `localhost:7687` with username `neo4j` and password `neo`.
You can override these values with environment variables.


```
NEO4J_HOST="bolt://localhost:7687" NEO4J_USER="neo4j" NEO4J_PASSWORD="neo" jupyter notebook
```

Navigate to http://localhost:8888/notebooks - the notebooks will be waiting!